### ISSUE TITLE
Improve Bottom and Create Imprint Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#11]
* Take out link (FSFE)
* Take out "Transparency"
* Create Imprint Page and link it on the bottom

**Comment by sayak119** [comment]
@mariobehling Can you give more information about the imprint page

**Comment by abishekvashok** [comment]
@mariobehling I would love tow rok on it but what's an impprint page? What do you expect, I mean is it a trader's page?
