### ISSUE TITLE
Expand button intercept the Spread the world section on click

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/publiccode.asia#118]
_Expand_ button below _supporting organization_ covered the _Spread the world_ section when clicked, besides the button itself is pretty useless since there's nothing to expand.

![image](https://user-images.githubusercontent.com/32614202/34381959-661e59fa-eb3e-11e7-8555-1dbab44d0f94.png)

Working on it.

**Comment by duttaditya18** [comment]
This issue is a copy of #106 
#117 Fixes this.
