### ISSUE TITLE
Authentication token blindy put in deploy.sh

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/publiccode.asia#144]
Authenticaion token is blindly present in `deploy.sh` which allows us to get signaturies of even persons who have not voted to be shown.

**Comment by 0x48piraj** [comment]
Can I do it please, as you did not claimed it ?

**Comment by abishekvashok** [comment]
@0x48piraj maybe we can co-operate on this. What do you say, but let's wait for someone like @mariobehling @hpdang or @fossasia/fossasia-gci to confirm that this was not intentional.

**Comment by 0x48piraj** [comment]
What was Intentional ? :open_mouth:
