### ISSUE TITLE
Back to the top button didnt work when pressed.

### ISSUE THREAD

**Issue by Chaitanyassr** [fossasia/publiccode.asia#185]
Back to the top button did work but slow down for 1st second when pressed. Instead it should make us reach to the top instantly(with smooth scroll) and not slow down at the start.

**Comment by Neilblaze** [comment]
Can I work upon this?

**Comment by Chaitanyassr** [comment]
> Can I work upon this?

sure , go ahead.

**Comment by khan-rehan** [comment]
Can I work on this?

**Comment by yash-93** [comment]
May i fix this? @Chaitanyassr

**Comment by Chaitanyassr** [comment]
@yash-93 @khan-rehan , This issue is old so it has been fixed now. I would be closing this. You can always work on another issue. Happy contributing.
