### ISSUE TITLE
In footer section of hindi translation of site.. there is a mistake in one line..

### ISSUE THREAD

**Issue by astromanish** [fossasia/publiccode.asia#197]
![Screenshot (15)](https://user-images.githubusercontent.com/57687267/92989405-c48b9880-f4f1-11ea-8c54-a2bca14a14a2.png)
is should be  "योगदान करने के लिए  आपका स्वागत है" instead

**Comment by astromanish** [comment]
can I work on this silly issue?😅

**Comment by SuryanshShahi** [comment]
Hi , I would like to work on this issue

**Comment by SuryanshShahi** [comment]
@astromanish the changes have been done please review.
