### ISSUE TITLE
"Server not found" error.

### ISSUE THREAD

**Issue by ps-19** [fossasia/publiccode.asia#214]
@mariobehling @jonasob @jordimas @comzeradd @mariobehling 
In https://github.com/fossasia/publiccode.asia#getting-involved "First of all, you'll need an account on github.com and become a FOSSASIA "member here" ." "member here" is directing to "server not" found error. URL is broken.

**Comment by mikini** [comment]
I think I was only involved in the FSFE PMPC repository, where did you find me in this repo?

The link is https://orgmanager.miguelpiedrafita.com/o/fossasia which seems to be to a defunct instance of something called [OrgManager](https://miguelpiedrafita.com/orgmanager) by Miguel Piedrafita at https://miguelpiedrafita.com/.

However, the [fossasia main site](http://fossasia.org/) links [to community.fossasia.org for "Become member"](https://community.fossasia.org/) so I guess that could be the correct destination now.

Have nothing to do with fossasia, however, so will not actively change this.
