### ISSUE TITLE
Clicking on the links for social media redirects - Implement without redirect.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#22]
Clicking on the social media links directs users to fsfe.org. Implement a sharing way without this redirect.

**Comment by sayak119** [comment]
![screencast_thursday-30-november-2017_05_41_03-ist](https://user-images.githubusercontent.com/28414920/33430382-637d99a2-d5f6-11e7-8c24-1050e6fedcdd.gif)

Its not redirecting to fsfe.org

**Comment by mariobehling** [comment]
As you can see in your gif, it is shortly connecting to fsfe.org.

**Comment by Kreijstal** [comment]
@sayak119 See the HTML source code that there are still references to fsfe.org

**Comment by mariobehling** [comment]
`<form action="https://fsfe.org/share" method="GET" class="share-buttons spread" target="_blank">
  <input name="popup" id="no-share-popup-spread" type="radio">
  <input name="ref" value="pmpc-spread" type="hidden">
  <input name="url" value="https://publiccode.asia/" type="hidden">
  <input id="sharetitle-spread" name="title" value="If it is public money, it should be public code as well! I support @fsfe's call for more #publiccode:" type="hidden">
  <input class="n" name="website" placeholder="Please do not put anything here">
`
