### ISSUE TITLE
Add Google and Linkedin as sharing options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#23]
- Add Google+
- Add Linkedin

**Comment by sayak119** [comment]
@mariobehling  i would like to work on this

**Comment by mariobehling** [comment]
@sayak119 Please only claim one issue at a time.

**Comment by engrravijain** [comment]
@sayak119 are you still working on this issue? if not can i ?

**Comment by sayak119** [comment]
@engrravijain You can work on the linked in part. I am already working on the google+ part

**Comment by engrravijain** [comment]
@sayak119 ohk I'll work on that

**Comment by 0x48piraj** [comment]
I'm on it :+1:
