### ISSUE TITLE
Create empty versions for Indian languages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#24]
Please add the language version for the major Indian languages.

The content can be added later, but the sample files should be created.

**Comment by sayak119** [comment]
@mariobehling I would  like to work on this issue

**Comment by sayak119** [comment]
`Error: While parsing config: (1406, 1): unexpected token`

Can you please help me with this. I get this when i run ./build.sh server . I have made a strings.hi.toml (for hindi) and added yaml files in site/data/share/hi . Also added hi in build.sh and made md files in site/content accordingly
