### ISSUE TITLE
Implement header style transparent/semi-transparent

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#28]
Implement the same functionality as in the transparent/semi-transparent header on FOSSASIA.org.
* Ensure there are two logo versions, that change the color
* Ensure the font changes the color as needed

![screenshot from 2017-11-30 14-20-21](https://user-images.githubusercontent.com/1583873/33432873-e636928a-d5d9-11e7-95f1-55893eba5b55.png)

**Comment by kubami9** [comment]
Working on it 👍

**Comment by kubami9** [comment]
I made a pull request :)
