### ISSUE TITLE
Substitute EURO Symbol with Dollar Symbol

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#60]
There is a EURO symbol. As more countries use the Dollar symbol in Asia it would be more suitable. Please change it.

![screenshot from 2017-12-05 23-51-26](https://user-images.githubusercontent.com/1583873/33635276-9b01c04a-da17-11e7-85ef-dec71c945c10.png)

**Comment by sayak119** [comment]
@mariobehling I would like to work on this issue
