### ISSUE TITLE
Hindi translation not working

### ISSUE THREAD

**Issue by Remorax** [fossasia/publiccode.asia#66]
On clicking Hindi translation, the site doesn't translate it. Instead it shows the page in English only.
Hindi translation needs to be added.
I would like to work on this :)

**Comment by mariobehling** [comment]
The content of this file is still missing: https://github.com/fossasia/publiccode.asia/blob/master/site/content/openinitiative.en.md

**Comment by Remorax** [comment]
I'll do that. 
Just wanted to confirm though, I have to copy the contents of that file to openinitiative.hi.md and then translate it, right?
