### ISSUE TITLE
Lack of template for issue or PR

### ISSUE THREAD

**Issue by Remorax** [fossasia/publiccode.asia#70]
There is no template for creating an issue or a PR. 
This needs to be created ASAP. 
I would like to work on this, and I'll make a PR for the same by tomorrow :)

**Comment by mariobehling** [comment]
This is not a traditional software project. So, we dont need the same kind of issue and PR templates. Closing it therefore as it is not relevant here.

**Comment by Remorax** [comment]
Alright. But I still feel there needs to be some kind of structure. 
For instance, an issue may need screenshots and steps to reproduce, while a PR may need screenshots and a description for the changes made.
Do let me know what should be done. Thanks :)
