### ISSUE TITLE
Make top left logos work in different language versions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#74]
The top left logo currently does not work in different languages.

![screenshot from 2017-12-08 15-55-45](https://user-images.githubusercontent.com/1583873/33771184-62f05f0c-dc30-11e7-8606-b0b40b80acdf.png)

**Comment by sayak119** [comment]
@mariobehling I would like to work on this issue

**Comment by Remorax** [comment]
I would like to work on this :)
