### ISSUE TITLE
Top logo color not changing on subpages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/publiccode.asia#93]
The top left logo changes the color when the page is scrolled. This only works on the start page.

![screenshot from 2017-12-13 22-46-43](https://user-images.githubusercontent.com/1583873/33964096-9cec76f2-e057-11e7-8ebe-36c7c44ed7ba.png)

**Comment by duttaditya18** [comment]
So. What should happen? It should not change color?

**Comment by Remorax** [comment]
I would like to work on this

**Comment by duttaditya18** [comment]
@Remorax Go on!
